### ISSUE TITLE
Update Anthropic Client

### ISSUE THREAD

**Issue by ghost** [xiahan4956/Auto_Claude_100k#2]
Anthropic changed their python sdk - making this code line outdated.

https://github.com/xiahan4956/Auto_Claude_100k/blob/1d34dd63d007992d58512f63ab4f6658579cee5c/autogpt/llm/llm_utils.py#L41

---

Would love to know if this might help - https://github.com/BerriAI/litellm

~Simple I/O library, that standardizes all the llm api calls to the OpenAI call

```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["ANTHROPIC_API_KEY"] = "anthropic key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# anthropic call
response = completion("claude-v-2", messages)

```

**Comment by ghost** [comment]
cc: @Torantulino @xiahan4956

**Comment by st1vms** [comment]
Hello, I recently improved the existing solutions, by fixing header consistency, adding auto session gathering using Firefox login and selenium, and auto user agent retrieval along with timezone.

My unofficial version of the API does currently work like a charm, it supports chat creation/deletion/retrieval and messages with attachments (with all the supported file types). It also let you handle a MessageRateLimit exception that provides you with the amount of seconds to sleep before next rateReset. 

Come have a try! Leave a :star: if you can : )

https://github.com/st1vms/unofficial-claude2-api

**Comment by xiahan4956** [comment]
fixed . You could clone main branch
